package com.venussystem.venusmobile.domain.scan;

import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

/** Local recognition vocabulary, not an exhaustive list of valid ingredients. */
public final class ScanIngredientVocabulary {
    private ScanIngredientVocabulary() { }
    public static final Set<String> NAMES = Collections.unmodifiableSet(new LinkedHashSet<>(
            Arrays.asList(
                    "AQUA",
                    "WATER",
                    "GLYCERIN",
                    "GLYCINE",
                    "PARFUM",
                    "FRAGRANCE",
                    "ALCOHOL",
                    "PROPANEDIOL",
                    "BUTANE",
                    "ISOBUTANE",
                    "PROPANE",
                    "CYCLOPENTASILOXANE",
                    "HELIANTHUS ANNUUS SEED OIL",
                    "OCTYLDODECANOL",
                    "DIMETHICONE",
                    "DIMETHICONOL",
                    "CARBOMER",
                    "TOCOPHEROL",
                    "NIACINAMIDE",
                    "PANTHENOL",
                    "SODIUM CHLORIDE",
                    "CALCIUM CHLORIDE",
                    "SODIUM HYDROXIDE",
                    "CITRIC ACID",
                    "LACTIC ACID",
                    "SALICYLIC ACID",
                    "BENZYL ALCOHOL",
                    "BENZYL SALICYLATE",
                    "LINALOOL",
                    "LIMONENE",
                    "HEXYL CINNAMAL",
                    "ALPHA-ISOMETHYL IONONE",
                    "COUMARIN",
                    "CITRONELLOL",
                    "GERANIOL",
                    "CITRAL",
                    "EUGENOL",
                    "SODIUM BENZOATE",
                    "POTASSIUM SORBATE",
                    "PHENOXYETHANOL",
                    "DISODIUM EDTA",
                    "MICA",
                    "TITANIUM DIOXIDE",
                    "IRON OXIDES",
                    "ZINC OXIDE",
                    "TALC",
                    "SILICA",
                    "KAOLIN",
                    "ALUMINA",
                    "PROPYLENE CARBONATE",
                    "CAPRYLYL GLYCOL",
                    "CETEARYL ALCOHOL",
                    "CETYL ALCOHOL",
                    "STEARYL ALCOHOL",
                    "GLYCERYL STEARATE",
                    "POLYQUATERNIUM-10",
                    "BEHENTRIMONIUM CHLORIDE",
                    "CETRIMONIUM CHLORIDE",
                    "SODIUM LAURYL SULFATE",
                    "SODIUM LAURETH SULFATE",
                    "COCAMIDOPROPYL BETAINE",
                    "COCO-GLUCOSIDE",
                    "DECYL GLUCOSIDE",
                    "SODIUM PCA",
                    "ARGININE",
                    "BIOTIN",
                    "CAFFEINE",
                    "SQUALANE",
                    "CINNAMAL",
                    "DISTEARDIMONIUM HECTORITE",
                    "PROPYLENE GLYCOL",
                    "BUTYLENE GLYCOL",
                    "CAPRYLIC/CAPRIC TRIGLYCERIDE",
                    "C12-15 ALKYL BENZOATE",
                    "ISOPROPYL MYRISTATE",
                    "ALUMINUM SESQUICHLOROHYDRATE",
                    "PPG-14 BUTYL ETHER",
                    "QUATERNIUM-18 HECTORITE",
                    "2-METHYL-5-CYCLOHEXYLPENTANOL",
                    "TOCOPHERYL ACETATE",
                    "GOSSYPIUM HERBACEUM SEED OIL",
                    "BUTYROSPERMUM PARKII BUTTER",
                    "MACADAMIA TERNIFOLIA SEED OIL",
                    "COCOS NUCIFERA FRUIT EXTRACT",
                    "CHAMOMILLA RECUTITA FLOWER EXTRACT",
                    "ALOE BARBADENSIS LEAF EXTRACT",
                    "CAMELLIA SINENSIS LEAF EXTRACT",
                    "CINNAMOMUM ZEYLANICUM BARK EXTRACT",
                    "COMMIPHORA EUROPAEA FRUIT OIL",
                    "ARGANIA SPINOSA KERNEL OIL",
                    "MYRRHA RESIN EXTRACT",
                    "LECITHIN",
                    "POLYGLYCERYL-3 DIISOSTEARATE",
                    "HYDROXYCITRONELLAL"
            )));
}

